### ISSUE TITLE
Additional _dt is getting appended for some fields related to time

### ISSUE THREAD

**Issue by qualys-suraj** [valllabh/ocsf-tool#15]
We have fields like start_time, end_time but in the generated proto we are getting fields start_time as well as start_time_dt, also same for time and end_time, _dt is getting appended which should not be appended.

![MicrosoftTeams-image (9)](https://github.com/valllabh/ocsf-tool/assets/137393909/8c16f118-4392-4aec-a822-fb89a9c101ab)

**Comment by valllabh** [comment]
This occurs because `start_time_dt` and `end_time_dt` are part of the **Date/Time** profile.
By default, all profiles will be active if no profiles are configured.
You might want to use **cloud** and **container** profiles for your context.

To configure the profile use the following URL.
https://github.com/valllabh/ocsf-tool?tab=readme-ov-file#to-set-profiles

This feature is available `v0.1.6` onwards.
