### ISSUE TITLE
The File Activity proto is receiving two additional fields—Attacks and Malware—that are not present in the OCSF schema for File Activity.

### ISSUE THREAD

**Issue by Surajgk007** [valllabh/ocsf-tool#16]
Will need to remove this 2 fields, Attacks and Malware

**Comment by valllabh** [comment]
This occurs because Attacks and Malware are part of the **Security Control** profile.
By default, all profiles will be active if no profiles are configured. You might want to use cloud and container profile for your context.

To configure the profile use the following URL.
https://github.com/valllabh/ocsf-tool?tab=readme-ov-file#to-set-profiles
